version: "3.3"
services:
  db:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
